### DISCUSSION TITLE
How to read logs on a remote server in the /var/log directory?

### DISCUSSION THREAD

**Discussion by collex100** [openobserve/agents#11] [General]
Friends, can you tell me how to read logs on a remote server in the /var/log directory?
For example, directories:
/var/log/nginx
/var/log/odoo

Which command should I run on the remote server?
Thanks!

![image](https://github.com/user-attachments/assets/8097b454-3cec-412f-a3db-3a925ec57b5a)

**Comment by hengfeiyang** [comment]
There are a lot of tools can do this:
https://openobserve.ai/docs/ingestion/logs/

Install any tools which you like and use it send logs to O2.

**Reply by collex100** [reply]
Thanks for the reply. 

Here is an example. 

By default, the application has a command that collects linux logs. 

```
curl -O https://raw.githubusercontent.com/openobserve/agents/main/linux/install.sh && chmod +x install.sh && sudo ./install.sh https://domain.com/api/default/ Ygddfgdfgdfgdfdfgdfgdf
```

Let's take this instruction
`https://openobserve.ai/docs/ingestion/logs/curl/`

Let's take the template of this command
```
curl http://localhost:5080/api/default/quickstart1/_json -i -u 'root@example.com:Complexpass#123' --data-binary "@k8slog_json.json
```

How do I specify reading of this log file?
`/var/log/odoo/odoo18.log`

Thanks!

**Comment by hengfeiyang** [comment]
Okay, you are asking for the agents. let me transfer it first.

**Comment by Manazsharma** [comment]
hi, so basically by running that script we are installing opentelemetry collector to collect and export logs & metrics from any linux machine . By default journald logs and Host metrics are configured, now to specify reading a specific log file you can add a https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/filelogreceiver/README.md to collect logs from a specific log file.

**Comment by hengfeiyang** [comment]
For the agents, we just installed a otel-collector in your local. you can find the config file:
`c:\otel-collector\otel-config.yaml`
You can add a new `filelog` under the section `receivers`, please check this document: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver#example---tailing-a-simple-json-file

**Reply by collex100** [reply]
Thanks for the recommendation.

It seems that the logic is simple. 

I added an entry to the file

`/etc/otel-config.yaml`

![image](https://github.com/user-attachments/assets/67c097cc-f3e9-423f-b2e2-894f11c19681)

And it looks like this:

```
receivers:
  journald:
    directory: /var/log/journal
  filelog/std:
    include: [ /var/log/**log ]
  filelog:
    include: [ /var/log/odoo/odoo18.log ]
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'
        severity:
          parse_from: attributes.sev
...
```

For some reason, I didn't get any effect on collecting logs.

I want to collect logs from a file `odoo18.log`


I tried adding lines to the .sh file.

```
cat > /etc/otel-config.yaml <<EOL
receivers:
  journald:
    directory: /var/log/journal
  filelog/std:
    include: [ /var/log/**log ]
  filelog:
    include: [ /var/log/odoo/odoo18.log ]
    operators:
      - type: regex_parser
        regex: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%d %H:%M:%S'
        severity:
          parse_from: attributes.sev
```

And I ran the script with the changed lines
```
./install.sh https://domain.com/api/default/ YWRtdfgdgdfgddfgdfgdfgdfgdfgdfgdfg
```
 These two methods did not have the effect of collecting logs. Is there a recommendation where I should look?

Thanks!
