### ISSUE TITLE
Installation failing on Unraid server

### ISSUE THREAD

**Issue by tknx** [openobserve/agents#14]
### Which OpenObserve functionalities are the source of the bug?

pipeline

### Is this a regression?

Yes

### Description

```
curl -O https://raw.githubusercontent.com/openobserve/agents/main/linux/install.sh && chmod +x install.sh && sudo ./install.sh https://api.openobserve.ai/api/_REDACTED-->_

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3318  100  3318    0     0  20622      0 --:--:-- --:--:-- --:--:-- 20737
**usermod: group 'systemd-journal' does not exist**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 69.6M  100 69.6M    0     0  17.1M      0  0:00:04  0:00:04 --:--:-- 19.0M
**./install.sh: line 114: /etc/systemd/system/otel-collector.service: No such file or directory
./install.sh: line 131: systemctl: command not found
./install.sh: line 132: systemctl: command not found
./install.sh: line 133: systemctl: command not found**
Otel-collector service started!
```

Is there an easier way to just get some basic syslog uploads going? The [instructions here](https://openobserve.ai/docs/ingestion/logs/syslog/#start-generating-test-syslog-data) refer to an Ingestion tab that I don't see.

### Please provide the exception or error you saw

```true
**./install.sh: line 114: /etc/systemd/system/otel-collector.service: No such file or directory
./install.sh: line 131: systemctl: command not found
./install.sh: line 132: systemctl: command not found
./install.sh: line 133: systemctl: command not found**
```

### Please provide the version you discovered this bug in (check about page for version information)

```true

```

**Comment by hengfeiyang** [comment]
thank you for report. we didn't support `Unraid`, even i didn't use it. 

It looks `Unraid` doesn't have `systemd`. Then you can manually install it:

1. Download binary from Github release.
2. Set an `.env` file in the dir which you want to run.
3. mv openobserve to the dir which have `.env`
4. `./openobserve`

**Comment by tknx** [comment]
Okay. Looks like lots of horror stories of pain using systemd with Slackware based distro so I guess I will try and figure out rsyslog functionality instead.  

I don't see the Ingestion tab when I log in to enable that route. Guess something else to figure out...

**Comment by reyo** [comment]
I had no problem running it on Unraid. Just make a simple go (/boot/config/go) script addition. Download the binary, move it to place, make the yaml and start it. I dropped journald stream, only **logs from /var/log

```
URL="yoururl"
AUTH_KEY="authkey"

pkill -f otelcol-contrib
rm /usr/local/bin/otelcol-contrib
rm /etc/otel-config.yaml

## OTEL

# Detect OS and architecture
OS=$(uname | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)
OTEL_VERSION="0.111.0"

if [ "$ARCH" = "x86_64" ]; then
    ARCH="amd64"
elif [ "$ARCH" = "aarch64" ]; then
    ARCH="arm64"
fi

# Construct the download URL
DOWNLOAD_URL="https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v${OTEL_VERSION}/otelcol-contrib_${OTEL_VERSION}_${OS}_${ARCH}.tar.gz"

# Download the otel-collector binary
curl -L $DOWNLOAD_URL -o otelcol-contrib.tar.gz

# Extract the binary
tar -xzf otelcol-contrib.tar.gz

# make the binary executable
chmod +x otelcol-contrib

# Move the binary to /usr/local/bin
mv otelcol-contrib /usr/local/bin/

# delete tar
rm otelcol-contrib.tar.gz


cat > /etc/otel-config.yaml <<EOL
receivers:
  filelog/std:
    include: [ /var/log/**log ]
    # start_at: beginning
  hostmetrics:
    root_path: /
    collection_interval: 30s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:          
      processes:
      # process: # a bug in the process scraper causes the collector to throw errors so disabling it for now
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 10s

extensions:
  zpages: {}

exporters:
  otlphttp/openobserve:
    endpoint: $URL
    headers:
      Authorization: "Basic $AUTH_KEY"
  otlphttp/openobserve_journald:
    endpoint: $URL
    headers:
      Authorization: "Basic $AUTH_KEY"
      stream-name: journald

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve]
    logs:
      receivers: [filelog/std]
      processors: [resourcedetection/system, memory_limiter, batch]
      exporters: [otlphttp/openobserve]
EOL



nohup /usr/local/bin/otelcol-contrib --config /etc/otel-config.yaml >/var/log/otelcol.log 2>&1 &
```
